-- Create a standalone table for the landing page waitlist
-- This table is completely separate from the main application tables (users, itineraries, etc.)
create table waitlist_signups (
  id bigint generated by default as identity primary key,
  email text not null unique,
  status text default 'pending' check (status in ('pending', 'invited', 'joined')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table waitlist_signups enable row level security;

-- Create a policy that allows anyone to insert their email (anon insert)
-- This is necessary for a public landing page
create policy "Enable insert for everyone" on waitlist_signups for insert with check (true);

-- Create a policy that allows only service_role (server-side) or specific admins to view.
-- For now, we disable public select to keep the list private.
-- No select policy for 'anon' means they cannot read the table, which is what we want.
